# Generated by Django 5.2.3 on 2025-06-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
