# Generated by Django 5.2.3 on 2025-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_start_date_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
