# Generated by Django 5.2.3 on 2025-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=0),
        ),
    ]
